### ISSUE TITLE
abnormal message is not abnormal

### ISSUE THREAD

**Issue by 155394551lzk** [josephkamel/VeReMi-Dataset#5]
Hi, sir,
The dataset in Downloadlink(updated on 2022/9/12) has some problems, The abnormal message  is not abnormal.
For example,  In "ConstPos" the Pos of the abnormal vehicle is not constant, In "ConstSpeed" the speed of the abnormal vehicle  is not constant, In "GridSybil" abnormal vehicle has only one senderPseudo, In "Dos" the sending frequency is normal messages', and so on.
Can you solve this problem？

**Comment by josephkamel** [comment]
Hi,
I just checked a few IDs and everything seems fine.
Please provide

**Comment by josephkamel** [comment]
Please provide examples of the issue

**Comment by 155394551lzk** [comment]
> Please provide examples of the issue

ConstPos0708：VeReMi_25200_28800_2022-9-11_20_45_32
 
![image](https://user-images.githubusercontent.com/60507390/191246244-f5f2f6dc-7983-4d2d-a463-2f51a7981b44.png)

ConstSpeed0708：VeReMi_25200_28800_2022-9-11_20_46_34
 
![image](https://user-images.githubusercontent.com/60507390/191246263-21469eac-2be5-463b-82a7-6fb2682bf98b.png)

MixAll0708: VeReMi_25200_28800_2022-9-11_12_51_1
"sender":10995 has only "senderPseudo":10109952
"sender":20871 has only "senderPseudo":10208712…
All Attacktype 16: GridSybil in MixAll0708 has only one senderPseudo

**Comment by josephkamel** [comment]
Every subset includes a file for the ground truth and a list of files containing the received message data.
The screenshots provided are taken from the file titled "traceGroundTruthJSON", this file includes the real data of every vehicle (i.e., before any modification).
The modified traces are the ones received by other vehicles, e.g., from traceJSON-21-19-A0-25208-7.json:

``` json
{"type":3,"rcvTime":25212.891887184214,"sendTime":25212.891887184214,"sender":15,"senderPseudo":10152,"messageID":30479,"pos":[1231.9853950705434,1082.1629732533502,0.0],"pos_noise":[4.684756928575876,4.948536626927654,0.0],"spd":[0.9334819605054899,-9.969161843280276,0.0],"spd_noise":[0.0016826269644783768,-0.017969954639237476,0.0],"acl":[0.21706314401459729,-2.3175836541552949,0.0],"acl_noise":[0.00030742432486314695,0.0033045283451604275,0.0],"hed":[0.09322777012651322,-0.9956448075881469,0.0],"hed_noise":[1.1168791274157615,3.3227829933692516,0.0]}
{"type":3,"rcvTime":25212.925708443185,"sendTime":25212.925708443185,"sender":27,"senderPseudo":10272,"messageID":30504,"pos":[131.18056223654595,892.595349234693,0.0],"pos_noise":[3.2604043050391016,3.4947214555033869,0.0],"spd":[0.0,0.0,0.0],"spd_noise":[0.0,0.0,0.0],"acl":[0.00005619968321259721,0.00005619968321259721,0.0],"acl_noise":[0.0,0.0,0.0],"hed":[0.9983713344239751,0.05704979053854121,0.0],"hed_noise":[0.5043615459039479,0.5043615459039479,0.0]}
{"type":2,"rcvTime":25213.0,"pos":[137.99094085048945,1099.123240045314,0.0],"pos_noise":[3.826851592294471,3.6847599186125254,0.0],"spd":[0.9763296495933871,-10.41760643342016,0.0],"spd_noise":[-0.00015325424712815238,0.0016352795776890287,0.0],"acl":[0.16526336533496023,-1.7633758621189837,0.0],"acl_noise":[0.00003257708994181376,0.0003476096152678868,0.0],"hed":[0.08377001337113198,-0.9964851152224002,0.0],"hed_noise":[11.659884784682987,36.43565790572505,0.0]}
{"type":3,"rcvTime":25213.891882586682,"sendTime":25213.891882586682,"sender":15,"senderPseudo":10152,"messageID":30631,"pos":[1231.9853950705434,1082.1629732533502,0.0],"pos_noise":[4.735932875823222,4.700050835829025,0.0],"spd":[1.1247227378269647,-12.01123933898111,0.0],"spd_noise":[0.0020272994690634365,-0.02165095429248265,0.0],"acl":[0.168684900182071,-1.8010684954803929,0.0],"acl_noise":[0.0003446725045850596,0.003680999653245174,0.0],"hed":[0.0931437861269599,-0.9956526679047946,0.0],"hed_noise":[1.0957257608635443,4.075580321374198,0.0]}
{"type":3,"rcvTime":25213.92570375963,"sendTime":25213.92570375963,"sender":27,"senderPseudo":10272,"messageID":30656,"pos":[131.18391664151384,892.5948888596096,0.0],"pos_noise":[3.1885053283161044,3.3717975956588179,0.0],"spd":[0.0,0.0,0.0],"spd_noise":[0.0,0.0,0.0],"acl":[0.00005619968321259721,0.00005619968321259721,0.0],"acl_noise":[0.0,0.0,0.0],"hed":[0.9983713344239751,0.05704979053854121,0.0],"hed_noise":[0.5043615459039479,0.5043615459039479,0.0]}
{"type":2,"rcvTime":25214.0,"pos":[138.9490802829797,1087.5720935689859,0.0],"pos_noise":[4.039960522929684,3.869056227766981,0.0],"spd":[1.1627969445584339,-12.407281532659799,0.0],"spd_noise":[-0.00018252447138053746,0.0019476037112860089,0.0],"acl":[0.14951923532447454,-1.5953787490548588,0.0],"acl_noise":[0.000029270224252385078,0.00031232413359698016,0.0],"hed":[0.07408534517563878,-0.9972519048014932,0.0],"hed_noise":[11.444480600231956,44.45668826761609,0.0]}
{"type":3,"rcvTime":25214.89189091283,"sendTime":25214.89189091283,"sender":15,"senderPseudo":10152,"messageID":30778,"pos":[1231.9853950705434,1082.1629732533502,0.0],"pos_noise":[4.736921215639723,4.743692224767596,0.0],"spd":[1.030774807995695,-13.906186781772153,0.0],"spd_noise":[0.001857949921808744,-0.025066698983308334,0.0],"acl":[0.15474292871498197,-2.087274675019605,0.0],"acl_noise":[0.00016934954725469236,0.003415744690825683,0.0],"hed":[0.07191701017259592,-0.9974106193779143,0.0],"hed_noise":[1.1060686012009545,4.925905356968423,0.0]}
```

Here we can see the vehicle 21 receiving the modified data sent by vehicle 15.

**Comment by 155394551lzk** [comment]
> Every subset includes a file for the ground truth and a list of files containing the received message data. The screenshots provided are taken from the file titled "traceGroundTruthJSON", this file includes the real data of every vehicle (i.e., before any modification). The modified traces are the ones received by other vehicles, e.g., from traceJSON-21-19-A0-25208-7.json:
> 
> ```json
> {"type":3,"rcvTime":25212.891887184214,"sendTime":25212.891887184214,"sender":15,"senderPseudo":10152,"messageID":30479,"pos":[1231.9853950705434,1082.1629732533502,0.0],"pos_noise":[4.684756928575876,4.948536626927654,0.0],"spd":[0.9334819605054899,-9.969161843280276,0.0],"spd_noise":[0.0016826269644783768,-0.017969954639237476,0.0],"acl":[0.21706314401459729,-2.3175836541552949,0.0],"acl_noise":[0.00030742432486314695,0.0033045283451604275,0.0],"hed":[0.09322777012651322,-0.9956448075881469,0.0],"hed_noise":[1.1168791274157615,3.3227829933692516,0.0]}
> {"type":3,"rcvTime":25212.925708443185,"sendTime":25212.925708443185,"sender":27,"senderPseudo":10272,"messageID":30504,"pos":[131.18056223654595,892.595349234693,0.0],"pos_noise":[3.2604043050391016,3.4947214555033869,0.0],"spd":[0.0,0.0,0.0],"spd_noise":[0.0,0.0,0.0],"acl":[0.00005619968321259721,0.00005619968321259721,0.0],"acl_noise":[0.0,0.0,0.0],"hed":[0.9983713344239751,0.05704979053854121,0.0],"hed_noise":[0.5043615459039479,0.5043615459039479,0.0]}
> {"type":2,"rcvTime":25213.0,"pos":[137.99094085048945,1099.123240045314,0.0],"pos_noise":[3.826851592294471,3.6847599186125254,0.0],"spd":[0.9763296495933871,-10.41760643342016,0.0],"spd_noise":[-0.00015325424712815238,0.0016352795776890287,0.0],"acl":[0.16526336533496023,-1.7633758621189837,0.0],"acl_noise":[0.00003257708994181376,0.0003476096152678868,0.0],"hed":[0.08377001337113198,-0.9964851152224002,0.0],"hed_noise":[11.659884784682987,36.43565790572505,0.0]}
> {"type":3,"rcvTime":25213.891882586682,"sendTime":25213.891882586682,"sender":15,"senderPseudo":10152,"messageID":30631,"pos":[1231.9853950705434,1082.1629732533502,0.0],"pos_noise":[4.735932875823222,4.700050835829025,0.0],"spd":[1.1247227378269647,-12.01123933898111,0.0],"spd_noise":[0.0020272994690634365,-0.02165095429248265,0.0],"acl":[0.168684900182071,-1.8010684954803929,0.0],"acl_noise":[0.0003446725045850596,0.003680999653245174,0.0],"hed":[0.0931437861269599,-0.9956526679047946,0.0],"hed_noise":[1.0957257608635443,4.075580321374198,0.0]}
> {"type":3,"rcvTime":25213.92570375963,"sendTime":25213.92570375963,"sender":27,"senderPseudo":10272,"messageID":30656,"pos":[131.18391664151384,892.5948888596096,0.0],"pos_noise":[3.1885053283161044,3.3717975956588179,0.0],"spd":[0.0,0.0,0.0],"spd_noise":[0.0,0.0,0.0],"acl":[0.00005619968321259721,0.00005619968321259721,0.0],"acl_noise":[0.0,0.0,0.0],"hed":[0.9983713344239751,0.05704979053854121,0.0],"hed_noise":[0.5043615459039479,0.5043615459039479,0.0]}
> {"type":2,"rcvTime":25214.0,"pos":[138.9490802829797,1087.5720935689859,0.0],"pos_noise":[4.039960522929684,3.869056227766981,0.0],"spd":[1.1627969445584339,-12.407281532659799,0.0],"spd_noise":[-0.00018252447138053746,0.0019476037112860089,0.0],"acl":[0.14951923532447454,-1.5953787490548588,0.0],"acl_noise":[0.000029270224252385078,0.00031232413359698016,0.0],"hed":[0.07408534517563878,-0.9972519048014932,0.0],"hed_noise":[11.444480600231956,44.45668826761609,0.0]}
> {"type":3,"rcvTime":25214.89189091283,"sendTime":25214.89189091283,"sender":15,"senderPseudo":10152,"messageID":30778,"pos":[1231.9853950705434,1082.1629732533502,0.0],"pos_noise":[4.736921215639723,4.743692224767596,0.0],"spd":[1.030774807995695,-13.906186781772153,0.0],"spd_noise":[0.001857949921808744,-0.025066698983308334,0.0],"acl":[0.15474292871498197,-2.087274675019605,0.0],"acl_noise":[0.00016934954725469236,0.003415744690825683,0.0],"hed":[0.07191701017259592,-0.9974106193779143,0.0],"hed_noise":[1.1060686012009545,4.925905356968423,0.0]}
> ```
> 
> Here we can see the vehicle 21 receiving the modified data sent by vehicle 15.

Get it! Thanks a lot

**Comment by 17860511195** [comment]
@155394551lzk Hello friend, I have some questions I would like to ask. Can you give me an email? The author may be too busy, haha。

**Comment by 155394551lzk** [comment]
Hello,
&nbsp; &nbsp; &nbsp;Bro, my email is ***@***.***, If you are convenient then you can contact my WeChat: 13658361748.

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "josephkamel/VeReMi-Dataset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月11日(星期二) 下午3:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [josephkamel/VeReMi-Dataset] abnormal message is not abnormal (Issue #5)





 
@155394551lzk Hello friend, I have some questions I would like to ask. Can you give me an email? The author may be too busy, haha。

**Comment by RDSandakelum** [comment]
> Hello, &nbsp; &nbsp; &nbsp;Bro, my email is ***@***.***, If you are convenient then you can contact my WeChat: 13658361748. &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "josephkamel/VeReMi-Dataset" ***@***.***&gt;; 发送时间:&nbsp;2023年4月11日(星期二) 下午3:42 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [josephkamel/VeReMi-Dataset] abnormal message is not abnormal (Issue #5) @155394551lzk Hello friend, I have some questions I would like to ask. Can you give me an email? The author may be too busy, haha。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

Hi, I am currently working on understanding the dataset, I have some questions. If you could give me your email, It would be really helpful for me to speed up my process. I just have a few questions regarding attack labeling, file naming conventions, etc.

**Comment by 155394551lzk** [comment]
202121045561@mail.scut.edu.cn

**Comment by RDSandakelum** [comment]
> @155394551lzk Hello friend, I have some questions I would like to ask. Can you give me an email? The author may be too busy, haha。

Hi, Is there a way for me to contact you, I have some clarifications to be made regarding the dataset. It would be really helpful for me if you could help. Thanks in advance.

**Comment by RDSandakelum** [comment]
> [202121045561@mail.scut.edu.cn](mailto:202121045561@mail.scut.edu.cn)

I mailed you the issues I have.

**Comment by RDSandakelum** [comment]
> Every subset includes a file for the ground truth and a list of files containing the received message data. The screenshots provided are taken from the file titled "traceGroundTruthJSON", this file includes the real data of every vehicle (i.e., before any modification). The modified traces are the ones received by other vehicles, e.g., from traceJSON-21-19-A0-25208-7.json:
> 
> ```json
> {"type":3,"rcvTime":25212.891887184214,"sendTime":25212.891887184214,"sender":15,"senderPseudo":10152,"messageID":30479,"pos":[1231.9853950705434,1082.1629732533502,0.0],"pos_noise":[4.684756928575876,4.948536626927654,0.0],"spd":[0.9334819605054899,-9.969161843280276,0.0],"spd_noise":[0.0016826269644783768,-0.017969954639237476,0.0],"acl":[0.21706314401459729,-2.3175836541552949,0.0],"acl_noise":[0.00030742432486314695,0.0033045283451604275,0.0],"hed":[0.09322777012651322,-0.9956448075881469,0.0],"hed_noise":[1.1168791274157615,3.3227829933692516,0.0]}
> {"type":3,"rcvTime":25212.925708443185,"sendTime":25212.925708443185,"sender":27,"senderPseudo":10272,"messageID":30504,"pos":[131.18056223654595,892.595349234693,0.0],"pos_noise":[3.2604043050391016,3.4947214555033869,0.0],"spd":[0.0,0.0,0.0],"spd_noise":[0.0,0.0,0.0],"acl":[0.00005619968321259721,0.00005619968321259721,0.0],"acl_noise":[0.0,0.0,0.0],"hed":[0.9983713344239751,0.05704979053854121,0.0],"hed_noise":[0.5043615459039479,0.5043615459039479,0.0]}
> {"type":2,"rcvTime":25213.0,"pos":[137.99094085048945,1099.123240045314,0.0],"pos_noise":[3.826851592294471,3.6847599186125254,0.0],"spd":[0.9763296495933871,-10.41760643342016,0.0],"spd_noise":[-0.00015325424712815238,0.0016352795776890287,0.0],"acl":[0.16526336533496023,-1.7633758621189837,0.0],"acl_noise":[0.00003257708994181376,0.0003476096152678868,0.0],"hed":[0.08377001337113198,-0.9964851152224002,0.0],"hed_noise":[11.659884784682987,36.43565790572505,0.0]}
> {"type":3,"rcvTime":25213.891882586682,"sendTime":25213.891882586682,"sender":15,"senderPseudo":10152,"messageID":30631,"pos":[1231.9853950705434,1082.1629732533502,0.0],"pos_noise":[4.735932875823222,4.700050835829025,0.0],"spd":[1.1247227378269647,-12.01123933898111,0.0],"spd_noise":[0.0020272994690634365,-0.02165095429248265,0.0],"acl":[0.168684900182071,-1.8010684954803929,0.0],"acl_noise":[0.0003446725045850596,0.003680999653245174,0.0],"hed":[0.0931437861269599,-0.9956526679047946,0.0],"hed_noise":[1.0957257608635443,4.075580321374198,0.0]}
> {"type":3,"rcvTime":25213.92570375963,"sendTime":25213.92570375963,"sender":27,"senderPseudo":10272,"messageID":30656,"pos":[131.18391664151384,892.5948888596096,0.0],"pos_noise":[3.1885053283161044,3.3717975956588179,0.0],"spd":[0.0,0.0,0.0],"spd_noise":[0.0,0.0,0.0],"acl":[0.00005619968321259721,0.00005619968321259721,0.0],"acl_noise":[0.0,0.0,0.0],"hed":[0.9983713344239751,0.05704979053854121,0.0],"hed_noise":[0.5043615459039479,0.5043615459039479,0.0]}
> {"type":2,"rcvTime":25214.0,"pos":[138.9490802829797,1087.5720935689859,0.0],"pos_noise":[4.039960522929684,3.869056227766981,0.0],"spd":[1.1627969445584339,-12.407281532659799,0.0],"spd_noise":[-0.00018252447138053746,0.0019476037112860089,0.0],"acl":[0.14951923532447454,-1.5953787490548588,0.0],"acl_noise":[0.000029270224252385078,0.00031232413359698016,0.0],"hed":[0.07408534517563878,-0.9972519048014932,0.0],"hed_noise":[11.444480600231956,44.45668826761609,0.0]}
> {"type":3,"rcvTime":25214.89189091283,"sendTime":25214.89189091283,"sender":15,"senderPseudo":10152,"messageID":30778,"pos":[1231.9853950705434,1082.1629732533502,0.0],"pos_noise":[4.736921215639723,4.743692224767596,0.0],"spd":[1.030774807995695,-13.906186781772153,0.0],"spd_noise":[0.001857949921808744,-0.025066698983308334,0.0],"acl":[0.15474292871498197,-2.087274675019605,0.0],"acl_noise":[0.00016934954725469236,0.003415744690825683,0.0],"hed":[0.07191701017259592,-0.9974106193779143,0.0],"hed_noise":[1.1060686012009545,4.925905356968423,0.0]}
> ```
> 
> Here we can see the vehicle 21 receiving the modified data sent by vehicle 15.

Hello! Is this data from constant position 0709 folder? I checked the same file in this folder with same messageID. but the data is different? I downloaded the data from the link you provided. Also, for the messageID 30479 position is same in groundTruth file and traceJSON-21-19-A0-25208-7.json. But according to the data you provided it should be different.
![1](https://github.com/josephkamel/VeReMi-Dataset/assets/72394338/867cce6b-f585-42d0-86ce-e7a6a2710839)
