### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by 17860511195** [josephkamel/VeReMi-Dataset#6]
Hi, I would like to use your dataset but I have some problems, can you help me with this?
1. is a file of the type traceGroundTruthJSON-7.json a V2I message and a file of the type traceJSON-9-7-A0-25202-7.json a V2V message?
2. Can you be more specific about the meaning of the file names? For example traceJSON-9-7-A0-25202-7. is it a normal message sent from car 7 to car 9? Why are there many sender numbers in the file.
3. how do I set the attack tag?
Looking forward to your reply, thanks!

**Comment by 17860511195** [comment]
Hi, I would like to use your dataset but I have some problems, can you help me with this?
1. is a file of the type traceGroundTruthJSON-7.json a V2I message and a file of the type traceJSON-9-7-A0-25202-7.json a V2V message?
2. Can you be more specific about the meaning of the file names? For example traceJSON-9-7-A0-25202-7. is it a normal message sent from car 7 to car 9? Why are there many sender numbers in the file.
3. how do I set the attack tag?
Looking forward to your reply, thanks!

Translated with www.DeepL.com/Translator (free version)

**Comment by 17860511195** [comment]
![image](https://user-images.githubusercontent.com/92134035/227220206-afbb0e05-178e-444b-9bac-df5912e7afef.png)
Hello, I found a problem with the data set. I intercepted two pieces of data (as shown in the figure). The first entry comes from the GroundTruth file, type=4; the second entry comes from the Json log file, type= 3. According to my understanding of this data set, this message is sent by the sender=45 to the vehicle and the roadside unit at the same time, and the sending time should be the same, and the sendtime of GroundTruth should be the rcvTime of the Json log file, so I think Something went wrong here, hope you can clarify.

**Comment by nayerayouness** [comment]
@17860511195 did you reach out for answers to your questions, if yes I appreciate if you share it with me

**Comment by josephkamel** [comment]
All the information on the generation of the dataset can be found in these 2 files:
- https://github.com/josephkamel/veins-f2md/blob/master/src/veins/modules/application/f2md/mdSupport/VeReMiPrintable.cc
- https://github.com/josephkamel/veins-f2md/blob/master/src/veins/modules/application/f2md/F2MDVeinsApp.cc

Three types of logs exist:
- TYPE_GPS 2 --> Data as detected by the sensors (found in traceJSONFile)
- TYPE_TAG 3 --> Data as received by nearby vehicles (found in traceJSONFile)
- TYPE_TRUTH_BEACON 4 --> Data as sent by vehicle  (found in traceGroundTruthJSONFile)

All the infomation on attacks can be found in these 2 files:
- https://github.com/josephkamel/veins-f2md/blob/master/src/veins/modules/application/f2md/mdEnumTypes/AttackTypes.h
- https://github.com/josephkamel/veins-f2md/blob/master/src/veins/modules/application/f2md/mdAttacks/MDAttack.cc

Here is a list of all the attacks:
1. Genuine
2. ConstPos
3. ConstPosOffset
4. RandomPos
5. RandomPosOffset
6. ConstSpeed
7. ConstSpeedOffset
8. RandomSpeed
9. RandomSpeedOffset
10. EventualStop
11. Disruptive
12. DataReplay
13. StaleMessages
14. DoS
15. DoSRandom
16. DoSDisruptive
17. GridSybil
18. DataReplaySybil
19. DoSRandomSybil
20. DoSDisruptiveSybil

For more information please check these 2 papers:
- https://hal.science/hal-02492739v1
- https://hal.science/hal-02527873
- https://theses.hal.science/tel-03102396

**Comment by 17860511195** [comment]
thank you！

**Comment by nayerayouness** [comment]
Does this mean, given this file name "traceJSON-9-7-A0-25202-7"
9 is the realID
7 is the parentID
A0 is the attack type -> legitimate
25202 is the simTime
7 is the curSlice

Just to confirm my understanding:

- realID is the sender ID of the messages in this file?
- if so, what about the sender column, what does it represent?
- where is the receiver ID?
- what is the parentID?
- Each sender ID has 1 attack ID? Or each sender can be identified with different attacks?
- Should the attack ID then be linked to each message ID, or Sender ID (from the file name or the records?)

Appreciate your help and reply

**Comment by 17860511195** [comment]
I have a new question again. Is there an attack related to the 'SendTime' field? There is an issue with the sending time in the traceJSON file.

**Comment by 17860511195** [comment]
@nayerayouness I think your understanding is correct, and I don't quite understand what the last 7 means.

**Comment by nayerayouness** [comment]
@17860511195 the last 7 is current slice for the high traffic (7h-9h) you will find only two slices 7 and 8 , and for the low traffic (14h-16h) you will find it 14 and 15. as far as I understand. 

did you get what is the values of the sender IDs  inside the files mean, if the sender ID is the one in the file name? 
and what about the receiver ID?

**Comment by 17860511195** [comment]
文件名的发送者是打标记使用的吧，每条BSM的发送者应该是文件中type为3的sender ID，接收者是文件名中的第二个数字？？（有可能是，这个地方我也不清楚）&nbsp;


小帅智
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Aekta ***@***.***&gt;; 
发送时间: 2023年5月25日(星期四) 中午1:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [josephkamel/VeReMi-Dataset] problem (Issue #6)






@17860511195最后7是高流量（7h-9h）的当前切片，您会发现只有两个切片7和8，而低流量（14h-16h）的当前切片是14和15。据我所知。

您得到文件中发送方ID的值了吗意思是，如果发送方ID是文件名中的那个？
接收者的身份呢

—
直接回复此邮件，在GitHub上查看，或者取消订阅.
***@***.***与&gt;.
