### ISSUE TITLE
More details request 

### ISSUE THREAD

**Issue by nayerayouness** [josephkamel/VeReMi-Dataset#7]
I would like to inquire about the following:
•**Documentation:** Is there any documentation available that provides a comprehensive description of the dataset, including the data collection methodology, variables or parameters included, and any preprocessing steps performed? 

•**Variable Definitions:** Could you kindly provide more details on the specific meanings and units of the variables included in the dataset? This will help me better understand and analyze the data.  

•**Misbehavior Labels:** I noticed that the dataset includes misbehavior labels. Is it the type variable in the JSON log files or the type variable in the ground truth JSON file, as I did not get what number indicates which attack? Could you please provide me with the specific types of misbehavior or attacks covered in the dataset? This information will be crucial for my research analysis. 
What I know from the original version of VeReMi dataset is:
- Type 1 : Constant Position
- Type 2: Constant Offset 
- Type 4: Random Position 
- Type 8: Random Offset 
- Type 16: Eventual Stop
and I would know more about your added attacks labels in the extended version of the dataset

**Comment by josephkamel** [comment]
All the information on the generation of the dataset can be found in these 2 files:
- https://github.com/josephkamel/veins-f2md/blob/master/src/veins/modules/application/f2md/mdSupport/VeReMiPrintable.cc
- https://github.com/josephkamel/veins-f2md/blob/master/src/veins/modules/application/f2md/F2MDVeinsApp.cc

Three types of logs exist:
- TYPE_GPS 2 --> Data as detected by the sensors (found in traceJSONFile)
- TYPE_TAG 3 --> Data as received by nearby vehicles (found in traceJSONFile)
- TYPE_TRUTH_BEACON 4 --> Data as sent by vehicle  (found in traceGroundTruthJSONFile)

All the infomation on attacks can be found in these 2 files:
- https://github.com/josephkamel/veins-f2md/blob/master/src/veins/modules/application/f2md/mdEnumTypes/AttackTypes.h
- https://github.com/josephkamel/veins-f2md/blob/master/src/veins/modules/application/f2md/mdAttacks/MDAttack.cc

Here is a list of all the attacks:
1. Genuine
2. ConstPos
3. ConstPosOffset
4. RandomPos
5. RandomPosOffset
6. ConstSpeed
7. ConstSpeedOffset
8. RandomSpeed
9. RandomSpeedOffset
10. EventualStop
11. Disruptive
12. DataReplay
13. StaleMessages
14. DoS
15. DoSRandom
16. DoSDisruptive
17. GridSybil
18. DataReplaySybil
19. DoSRandomSybil
20. DoSDisruptiveSybil

For more information please check these 3 papers:
- https://hal.science/hal-02492739v1
- https://hal.science/hal-02527873
- https://theses.hal.science/tel-03102396

**Comment by nayerayouness** [comment]
@josephkamel Thank you

**Comment by nayerayouness** [comment]
Does this mean, given this file name "traceJSON-9-7-A0-25202-7"
9 is the realID
7 is the parentID
A0 is the attack type -> legitimate
25202 is the simTime
7 is the curSlice

Just to confirm my understanding:

- realID is the sender ID of the messages in this file?
- if so, what about the sender column, what does it represent?
- where is the receiver ID?
- what is the parentID?
- Each sender ID has 1 attack ID? Or each sender can be identified with different attacks?
- Should the attack ID then be linked to each message ID, or Sender ID (from the file name or the records?)

Appreciate your help and reply

**Comment by Enough7** [comment]
Hi @josephkamel,
the `TESTING RESULTS` from table 3 in your [Veremi-Extension-Paper](https://hal.science/hal-02492739v1) Page 6/7, do their originate from your [src/veins/modules/application/f2md/mdChecks](https://github.com/josephkamel/veins-f2md/tree/master/src/veins/modules/application/f2md/mdChecks) directory or did you use your [machine-learning-server](https://github.com/josephkamel/F2MD/tree/master/machine-learning-server)?
